export bibm=${bibm:-`readlink -f ../..`}
export bindir="$bibm/scripts/bin"
#export virtuosohome=${virtuosohome:-`readlink -f $bibm/../../../`}
export virtuosohome=${VIRTDEV_HOME:-/home/virtuoso}
export dbgen=${dbgen:-$virtuosohome/binsrc/tests/tpc-h/dbgen}
export virtuosobin=${virtuosobin:-$virtuosohome/bin}
export virtuoso=${virtuoso:-$virtuosobin/virtuoso}
export isql=${isql:-$virtuosobin/isql}
hport=`expr $PORT + 7000`
export HTTPPORT=${HTTPPORT:-$hport}
